[package]
name = "basename"
version = "0.0.1"
authors = []
license = "MIT"
build = "../#common/mkmain.rs"

[lib]
name = "uu_basename"
path = "src/basename.rs"

[dependencies]
uucore = "0.0.1"

[[bin]]
name = "basename"
path = "../#common/uumain.rs"
