[package]
name = "dirname"
version = "0.0.1"
authors = []
license = "MIT"
build = "../#common/mkmain.rs"

[lib]
name = "uu_dirname"
path = "src/dirname.rs"

[dependencies]
libc = "0.2.42"
uucore = "0.0.1"

[[bin]]
name = "dirname"
path = "../#common/uumain.rs"
