[package]
name = "groups"
version = "0.0.3"
authors = []
license = "MIT"
build = "../../common/mkmain.rs"

[lib]
name = "uu_groups"
path = "src/groups.rs"

[dependencies]
uucore = { version = "0.0.2", features = ["entries"] }

[[bin]]
name = "groups"
path = "../../common/uumain.rs"
