[package]
name = "cksum"
version = "0.0.3"
authors = []
license = "MIT"

[lib]
name = "uu_cksum"
path = "src/cksum.rs"

[dependencies]
libc = "0.2.42"
uucore = "0.0.2"

[[bin]]
name = "cksum"
path = "../../common/uumain.rs"
