[package]
name = "truncate"
version = "0.0.3"
authors = []
license = "MIT"
build = "../#common/mkmain.rs"

[lib]
name = "uu_truncate"
path = "src/truncate.rs"

[dependencies]
getopts = "0.2.18"
uucore = "0.0.1"

[[bin]]
name = "truncate"
path = "../#common/uumain.rs"
