[package]
name = "who"
version = "0.0.1"
authors = []
build = "../#common/mkmain.rs"

[lib]
name = "uu_who"
path = "who.rs"

[dependencies]
uucore = { version = "0.0.1", features = ["utmpx"] }
## optional
clippy = { version = "0.0.212", optional = true }

[[bin]]
name = "who"
path = "../#common/uumain.rs"
