[package]
name = "base64"
version = "0.0.1"
authors = []
license = "MIT"
build = "../#common/mkmain.rs"

[lib]
name = "uu_base64"
path = "base64.rs"

[dependencies]
uucore = { version = "0.0.1", features = ["encoding"] }

[[bin]]
name = "base64"
path = "../#common/uumain.rs"
