[package]
name = "du"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_du"
path = "du.rs"

[dependencies]
time = "0.1.40"
uucore = { git = "https://github.com/rivy/rust.uucore", branch = "rivy-local.globwalk" }

[[bin]]
name = "du"
path = "../../uumain.rs"
