[package]
name = "du"
version = "0.0.3"
authors = []
license = "MIT"
build = "../#common/mkmain.rs"

[lib]
name = "uu_du"
path = "src/du.rs"

[dependencies]
time = "0.1.40"
uucore = "0.0.1"

[[bin]]
name = "du"
path = "../#common/uumain.rs"
