[package]
name = "wc"
version = "0.0.3"
authors = []
license = "MIT"
build = "../../common/mkmain.rs"

[lib]
name = "uu_wc"
path = "src/wc.rs"

[dependencies]
getopts = "0.2.18"
uucore = "0.0.2"

[[bin]]
name = "wc"
path = "../../common/uumain.rs"
