[package]
name = "relpath"
version = "0.0.1"
authors = []
build = "../#common/mkmain.rs"

[lib]
name = "uu_relpath"
path = "relpath.rs"

[dependencies]
getopts = "0.2.18"
uucore = { version = "0.0.1", features = ["fs"] }

[[bin]]
name = "relpath"
path = "../#common/uumain.rs"
