[package]
name = "numfmt"
version = "0.0.3"
authors = []
license = "MIT"
build = "../#common/mkmain.rs"

[lib]
name = "uu_numfmt"
path = "src/numfmt.rs"

[dependencies]
getopts = "0.2.18"
uucore = "0.0.1"

[[bin]]
name = "numfmt"
path = "../#common/uumain.rs"
