[package]
name = "comm"
version = "0.0.3"
authors = []
license = "MIT"
build = "../#common/mkmain.rs"

[lib]
name = "uu_comm"
path = "src/comm.rs"

[dependencies]
getopts = "0.2.18"
libc = "0.2.42"
uucore = "0.0.1"

[[bin]]
name = "comm"
path = "../#common/uumain.rs"
