[package]
name = "factor"
version = "0.0.1"
authors = []
license = "MIT"

[lib]
name = "uu_factor"
path = "src/factor.rs"

[dependencies]
rand = "0.5"
uucore = "0.0.1"

[[bin]]
name = "factor"
path = "../#common/uumain.rs"
