[package]
name = "mktemp"
version = "0.0.1"
authors = []
license = "MIT"
build = "../#common/mkmain.rs"

[lib]
name = "uu_mktemp"
path = "mktemp.rs"

[dependencies]
getopts = "0.2.18"
rand = "0.5"
tempfile = "2.1.5"
uucore = "0.0.1"

[[bin]]
name = "mktemp"
path = "../#common/uumain.rs"
