[package]
name = "realpath"
version = "0.0.1"
authors = []
license = "MIT"
build = "../#common/mkmain.rs"

[lib]
name = "uu_realpath"
path = "src/realpath.rs"

[dependencies]
getopts = "0.2.18"
uucore = { version = "0.0.1", features = ["fs"] }

[[bin]]
name = "realpath"
path = "../#common/uumain.rs"
