[package]
name = "rm"
version = "0.0.3"
authors = []
license = "MIT"
build = "../../common/mkmain.rs"

[lib]
name = "uu_rm"
path = "src/rm.rs"

[dependencies]
getopts = "0.2.18"
walkdir = "2.2.8"
remove_dir_all = "0.5.1"
uucore = "0.0.2"

[[bin]]
name = "rm"
path = "../../common/uumain.rs"
