[package]
name = "true"
version = "0.0.1"
authors = []
license = "MIT"
build = "../#common/mkmain.rs"

[lib]
name = "uu_true"
path = "src/true.rs"

[dependencies]
uucore = "0.0.1"

[[bin]]
name = "true"
path = "../#common/uumain.rs"
