[package]
name = "mknod"
version = "0.0.3"
authors = []
license = "MIT"
build = "../#common/mkmain.rs"

[lib]
name = "uu_mknod"
path = "src/mknod.rs"

[dependencies]
getopts = "0.2.18"
libc = "^0.2.42"
uucore = "0.0.1"

[[bin]]
name = "mknod"
path = "../#common/uumain.rs"
