[package]
name = "logname"
version = "0.0.3"
authors = []
license = "MIT"
build = "../../common/mkmain.rs"

[lib]
name = "uu_logname"
path = "src/logname.rs"

[dependencies]
libc = "0.2.42"
uucore = "0.0.2"

[[bin]]
name = "logname"
path = "../../common/uumain.rs"
