[package]
name = "tr"
version = "0.0.1"
authors = []
license = "MIT"
build = "../#common/mkmain.rs"

[lib]
name = "uu_tr"
path = "tr.rs"

[dependencies]
bit-set = "0.5.0"
fnv = "1.0.5"
getopts = "0.2.18"
uucore = "0.0.1"

[[bin]]
name = "tr"
path = "../#common/uumain.rs"
