[package]
name = "groups"
version = "0.0.1"
authors = []
build = "../#common/mkmain.rs"

[lib]
name = "uu_groups"
path = "groups.rs"

[dependencies]
uucore = { version = "0.0.1", features = ["entries"] }

[[bin]]
name = "groups"
path = "../#common/uumain.rs"
