[package]
name = "stat"
version = "0.0.1"
authors = []
license = "MIT"
build = "../#common/mkmain.rs"

[lib]
name = "uu_stat"
path = "src/stat.rs"

[dependencies]
getopts = "0.2.18"
time = "0.1.40"
uucore = { version = "0.0.1", features = ["entries"] }

[[bin]]
name = "stat"
path = "../#common/uumain.rs"
