[package]
name = "kill"
version = "0.0.1"
authors = []
license = "MIT"
build = "../#common/mkmain.rs"

[lib]
name = "uu_kill"
path = "src/kill.rs"

[dependencies]
libc = "0.2.42"
uucore = { version = "0.0.1", features = ["signals"] }

[[bin]]
name = "kill"
path = "../#common/uumain.rs"
