[package]
name = "ln"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_ln"
path = "ln.rs"

[dependencies]
libc = "0.2.42"
uucore = { git = "https://github.com/rivy/rust.uucore", branch = "rivy-local.globwalk" }

[[bin]]
name = "ln"
path = "../../uumain.rs"
