[package]
name = "libstdbuf"
version = "0.0.1"
authors = []
license = "MIT"

[lib]
name = "libstdbuf"
path = "src/libstdbuf.rs"
# XXX: the rlib is just to prevent Cargo from spitting out a warning
crate-type = ["cdylib", "rlib"]

[dependencies]
cpp = "0.4"
libc = "0.2"
uucore = "0.0.1"

[build-dependencies]
cpp_build = "0.4"
