[package]
name = "false"
version = "0.0.3"
authors = []
license = "MIT"
build = "../#common/mkmain.rs"

[lib]
name = "uu_false"
path = "src/false.rs"

[dependencies]
uucore = "0.0.1"

[[bin]]
name = "false"
path = "../#common/uumain.rs"
