[package]
name = "pathchk"
version = "0.0.3"
authors = []
license = "MIT"
build = "../../common/mkmain.rs"

[lib]
name = "uu_pathchk"
path = "src/pathchk.rs"

[dependencies]
getopts = "0.2.18"
libc = "0.2.42"
uucore = "0.0.2"

[[bin]]
name = "pathchk"
path = "../../common/uumain.rs"
