[package]
name = "link"
version = "0.0.1"
authors = []
license = "MIT"
build = "../#common/mkmain.rs"

[lib]
name = "uu_link"
path = "src/link.rs"

[dependencies]
libc = "0.2.42"
uucore = "0.0.1"

[[bin]]
name = "link"
path = "../#common/uumain.rs"
