[package]
name = "hostname"
version = "0.0.3"
authors = []
license = "MIT"
build = "../#common/mkmain.rs"

[lib]
name = "uu_hostname"
path = "src/hostname.rs"

[dependencies]
getopts = "0.2"
libc = "0.2.42"
uucore = "0.0.1"
winapi = { version = "0.3", features = ["sysinfoapi", "winsock2"] }

[[bin]]
name = "hostname"
path = "../#common/uumain.rs"
