[package]
name = "uptime"
version = "0.0.3"
authors = []
license = "MIT"
build = "../../common/mkmain.rs"

[lib]
name = "uu_uptime"
path = "src/uptime.rs"

[dependencies]
getopts = "0.2.18"
time = "0.1.40"
uucore = { version = "0.0.2", features = ["utmpx"] }

[[bin]]
name = "uptime"
path = "../../common/uumain.rs"
