[package]
name = "head"
version = "0.0.1"
authors = []
license = "MIT"
build = "../#common/mkmain.rs"

[lib]
name = "uu_head"
path = "head.rs"

[dependencies]
libc = "0.2.42"
uucore = "0.0.1"

[[bin]]
name = "head"
path = "../#common/uumain.rs"
