[package]
name = "cut"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_cut"
path = "cut.rs"

[dependencies]
uucore = { git = "https://github.com/rivy/rust.uucore", branch = "rivy-local.globwalk" }

[[bin]]
name = "cut"
path = "../../uumain.rs"
