[package]
name = "users"
version = "0.0.3"
authors = []
license = "MIT"
build = "../../common/mkmain.rs"

[lib]
name = "uu_users"
path = "src/users.rs"

[dependencies]
getopts = "0.2.18"
uucore = { version = "0.0.2", features = ["utmpx"] }

[[bin]]
name = "users"
path = "../../common/uumain.rs"
