[package]
name = "uname"
version = "0.0.3"
authors = []
license = "MIT"
build = "../#common/mkmain.rs"

[lib]
name = "uu_uname"
path = "src/uname.rs"

[dependencies]
clap = "2.32.0"
platform-info = "0.0.1"
uucore = "0.0.1"

[[bin]]
name = "uname"
path = "../#common/uumain.rs"
