[package]
name = "expand"
version = "0.0.3"
authors = []
license = "MIT"
build = "../../common/mkmain.rs"

[lib]
name = "uu_expand"
path = "src/expand.rs"

[dependencies]
getopts = "0.2.18"
unicode-width = "0.1.5"
uucore = "0.0.2"

[[bin]]
name = "expand"
path = "../../common/uumain.rs"
