[package]
name = "dircolors"
version = "0.0.3"
authors = []
license = "MIT"
build = "../#common/mkmain.rs"

[lib]
name = "uu_dircolors"
path = "src/dircolors.rs"

[dependencies]
glob = "0.3.0"
uucore = "0.0.1"

[[bin]]
name = "dircolors"
path = "../#common/uumain.rs"
