[package]
name = "cut"
version = "0.0.3"
authors = []
license = "MIT"
build = "../../common/mkmain.rs"

[lib]
name = "uu_cut"
path = "src/cut.rs"

[dependencies]
uucore = "0.0.2"

[[bin]]
name = "cut"
path = "../../common/uumain.rs"
