[package]
name = "join"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_join"
path = "join.rs"

[dependencies]
clap = "2.32.0"
uucore = { git = "https://github.com/rivy/rust.uucore", branch = "rivy-local.globwalk" }

[[bin]]
name = "join"
path = "../../uumain.rs"
