[package]
name = "stdbuf"
version = "0.0.1"
authors = []
license = "MIT"
build = "build.rs"

[lib]
name = "uu_stdbuf"
path = "src/stdbuf.rs"

[dependencies]
getopts = "0.2.18"
tempdir = "0.3.7"
uucore = "0.0.2"

[build-dependencies]
cargo_metadata = "0.9.1"
libstdbuf = { path="src/libstdbuf" }

[[bin]]
name = "stdbuf"
path = "../../common/uumain.rs"
