[package]
name = "tty"
version = "0.0.3"
authors = []
license = "MIT"
build = "../#common/mkmain.rs"

[lib]
name = "uu_tty"
path = "src/tty.rs"

[dependencies]
getopts = "0.2.18"
libc = "0.2.42"
uucore = { version = "0.0.1", features = ["fs"] }

[[bin]]
name = "tty"
path = "../#common/uumain.rs"
