[package]
name = "chroot"
version = "0.0.3"
authors = []
license = "MIT"
build = "../#common/mkmain.rs"

[lib]
name = "uu_chroot"
path = "src/chroot.rs"

[dependencies]
getopts = "0.2.18"
uucore = { version = "0.0.1", features = ["entries"] }

[[bin]]
name = "chroot"
path = "../#common/uumain.rs"
